[project]
name = "prjpythonuv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.1"
dependencies = [
    "ruff>=0.8.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]
